version: '3.8'

services:
  frontend:
    build:
      context: ./public
      dockerfile: Dockerfile
    container_name: minimal-ai-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - api

  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: minimal-ai-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    # Don't use env_file in production - set via Coolify UI
    environment:
      - NODE_ENV=production
      # Other env vars will be set via Coolify interface